### ISSUE TITLE
Revision doesn't like certain words in certain regions

### ISSUE THREAD

**Issue by deathau** [banool/auslan_dictionary#63]
I ran into an edge case where the revision section doesn't load, resulting in just a grey screen.
The case I found was:
- The word "how" in my favourites
- Additional sign regions: Southern *and* VIC

If I remove "how" from my favourites then set the region to one or the other and add it back, it works fine, but when I pick both then come back to the revision tab, it doesn't load.

Hopefully it's not too arduous to replicate and pin down.

**Comment by banool** [comment]
Thanks for the detailed description on how to reproduce the issue, I'll take a look soon!

**Comment by banool** [comment]
The detailed repro steps were super useful. I have fixed this issue with two changes:

- 40178c1e1e6babe2dc2409efeef7a6171d525a2a: This is a defensive change. Previously it was possible to add master flashcards with the same key, which causes the dolphin instance to throw. I would like to remove all duplicate keys where possible but this should defend against any issues.
- d86c23bb419930cd9b2da1c23fc3e228ed1fa251: This fixes the root cause, where I was adding the same subword multiple times while building the subwords based on the region filtering.

Expect the fix to roll out soon. Thanks!
